In [1]:
import pandas as pd
import numpy as np

import nltk
from nltk.corpus import stopwords
from nltk.probability import FreqDist

from wordcloud import WordCloud, STOPWORDS, ImageColorGenerator

import matplotlib as mpl
import matplotlib.pyplot as plt

from sklearn.naive_bayes import GaussianNB, MultinomialNB, ComplementNB, BernoulliNB, CategoricalNB
from sklearn.linear_model import SGDClassifier
from sklearn import tree
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier, GradientBoostingClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score

from sklearn import tree
from scipy.spatial import distance
import time
import funcoes_uteis

from gensim.models import word2vec

In [2]:
vect_bag = CountVectorizer()

In [3]:
df_articles = pd.read_csv('stemmed_words/labeled_and_stemmed_articles2.csv', sep='\t')


In [53]:
df_articles.date.min(), df_articles.date.max()

('2016-04-01', '2016-06-30')

In [4]:
df_articles[df_articles.link.str.contains('mercado')].shape, df_articles.shape

((520, 11), (1317, 11))

In [7]:
df_articles[df_articles.indice == 0].shape

(19, 11)

In [36]:
df_train = pd.concat([df_articles[df_articles.indice == 0].sample(19), df_articles[df_articles.indice == 1].sample(50), df_articles[df_articles.indice == -1].sample(50)], ignore_index=True)
# df_train = df_articles[df_articles.link.str.contains('mercado')]


In [37]:
tokens_stemmer = df_train.stemm

In [38]:
vect_bag = CountVectorizer()
docs_bag = vect_bag.fit_transform([' '.join(tokens_stemmer)])

frase_count_vec = []
frase_count_vec.append(docs_bag.todense()[0])

vect_bag.get_feature_names_out()


array(['abaix', 'abastec', 'abat', ..., 'zumvel', 'zwi', 'zyh'],
      dtype=object)

In [39]:

vec_contents = vect_bag.fit_transform(df_train.stemm).toarray()


In [40]:

X_train, X_test, y_train, y_test = train_test_split(vec_contents, df_train.indice)

In [41]:
vect_bag.get_feature_names_out()

array(['abaix', 'abastec', 'abat', ..., 'zumvel', 'zwi', 'zyh'],
      dtype=object)

In [42]:
gnb = GaussianNB(var_smoothing=1e-110)
gnb.fit(X_train, y_train)

cross_val_score(gnb, X_test, y_test, cv=3)

d:\Estudos\ML\venv\lib\site-packages\sklearn\model_selection\_split.py:676: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=3.
  warnings.warn(


array([0.6, 0.5, 0.5])

In [43]:
pd.Series(y_train).unique()

array([ 0,  1, -1], dtype=int64)

In [44]:
gnb = MultinomialNB(alpha=0.1)
gnb.fit(X_train, y_train)

cross_val_score(gnb, X_test, y_test, cv=3)

d:\Estudos\ML\venv\lib\site-packages\sklearn\model_selection\_split.py:676: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=3.
  warnings.warn(


array([0.5, 0.5, 0.4])

In [45]:
clf = tree.DecisionTreeClassifier()
clf = clf.fit(X_train, y_train)

cross_val_score(clf, X_test, y_test, cv=5, )

d:\Estudos\ML\venv\lib\site-packages\sklearn\model_selection\_split.py:676: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(


array([0.5       , 0.66666667, 0.16666667, 0.5       , 0.66666667])

In [46]:
clf = RandomForestClassifier(criterion ='gini')
clf = clf.fit(X_train, y_train)

cross_val_score(clf, X_test, y_test, cv=3)

d:\Estudos\ML\venv\lib\site-packages\sklearn\model_selection\_split.py:676: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=3.
  warnings.warn(


array([0.5, 0.5, 0.5])

In [47]:
clf = AdaBoostClassifier()
clf = clf.fit(X_train, y_train)

cross_val_score(clf, X_test, y_test, cv=3)

d:\Estudos\ML\venv\lib\site-packages\sklearn\model_selection\_split.py:676: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=3.
  warnings.warn(


array([0.6, 0.4, 0.6])

In [48]:
clf = GradientBoostingClassifier(n_estimators=100, learning_rate=1.0, max_depth=1, random_state=0)
clf = clf.fit(X_train, y_train)

cross_val_score(clf, X_test, y_test, cv=3)

d:\Estudos\ML\venv\lib\site-packages\sklearn\model_selection\_split.py:676: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=3.
  warnings.warn(


array([0.4, 0.5, 0.4])

In [49]:
clf = SGDClassifier()
clf = clf.fit(X_train, y_train)

cross_val_score(clf, X_test, y_test, cv=3)


d:\Estudos\ML\venv\lib\site-packages\sklearn\model_selection\_split.py:676: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=3.
  warnings.warn(


array([0.7, 0.6, 0.3])

In [50]:
clf = SGDClassifier(loss='modified_huber', )
clf = clf.fit(X_train, y_train)

cross_val_score(clf, X_test, y_test, cv=3)


d:\Estudos\ML\venv\lib\site-packages\sklearn\model_selection\_split.py:676: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=3.
  warnings.warn(


array([0.7, 0.6, 0.2])

In [52]:
clf = SGDClassifier(loss='perceptron')
clf = clf.fit(X_train, y_train)

cross_val_score(clf, X_test, y_test, cv=5)

d:\Estudos\ML\venv\lib\site-packages\sklearn\model_selection\_split.py:676: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(


array([0.66666667, 0.66666667, 0.83333333, 0.33333333, 0.5       ])